// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xjxvztewixgekjlqxlbq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhqeHZ6dGV3aXhnZWtqbHF4bGJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5MDQ3ODIsImV4cCI6MjA3NDQ4MDc4Mn0.eYZBg2R5MIMXWOL_AJE8de3rJ60SQUE0ypCFYdNS91A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});